name: Terraform Action
description: Deploy Terraform resources to GCP

inputs:
  config-path:
    description: Path to the Terraform configuration file
    required: true
  env:
    description: Environment name (e.g., prod, beta, dev)
    required: true

runs:
    using: "composite"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/172250116490/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: ${{ inputs.SA_NAME }}
          project_id: oceanic-muse-464012-k2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        shell: bash
        run: terraform init -backend-config="${{ vars.env }}/${{ vars.env }}.backend.config"
        working-directory: terraform
        env:
          env: ${{ inputs.env }}

      - name: Terraform Apply
        shell: bash
        run: |
          terraform apply -auto-approve \
          -var-file="${{ vars.env }}/${{ vars.env }}.tfvars"
        working-directory: terraform
