project_id = "oceanic-muse-464012-k2"
region     = "europe-west1"
image      = "europe-west1-docker.pkg.dev/oceanic-muse-464012-k2/beta-repo/pythonimg"
service_name = "python-service-beta"
env = "beta"
service_account_env = "beta-13@oceanic-muse-464012-k2.iam.gserviceaccount.com"