name: Automation Staging Workflow

on:
  pull_request:
    branches:
        - staging

permissions:
  id-token: write
  contents: read

jobs:
    sleep-script:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./sleepscript
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Run Sleep Script
            run: ./50percent.sh  
  