name: Call 2 actions

on:
  pull_request:
    branches:
      - main
      - develop
      - staging
    paths:
      - 'app/**'
  workflow_dispatch:
     
permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use env and sa_name
        run: |
          echo "ENV is ${{ inputs.env }}"
          echo "SA is ${{ inputs.SA_NAME }}"

      - name: Build and Push Docker Image
        uses: ./.github/actions/build-push
        with:
          env: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'staging' && 'beta' || github.ref_name == 'develop' && 'dev'  }}

  terraform:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy Terraform Resources
        uses: ./.github/actions/deploy-terraform
        with:
          env: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'staging' && 'beta' || github.ref_name == 'develop' && 'dev' }}
          config-path: 'terraform/${{ vars.env }}.tfvars'

  