name: Deploy to GCP with Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Select environment to deploy"
        required: true
        options:
          - dev
          - beta

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment name
        id: set-env
        run: echo "env_name=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT

      - name: Select service account
        id: sa
        run: |
          if [[ "${{ steps.set-env.outputs.env_name }}" == "dev" ]]; then
            echo "sa_dev_beta=${{ vars.DEV_SA }}" >> $GITHUB_OUTPUT
          else
            echo "sa_dev_beta=${{ vars.BETA_SA }}" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/172250116490/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: ${{ steps.sa.outputs.sa_dev_beta }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.backend.config"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve \
              -var="secret_env_value=${{ secrets.SECRET_ENV_VALUE }}" \
              -var-file="${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.tfvars"
        working-directory: terraform
