name: Call 2 reusable workflow

on:
  pull_request:
    branches:
      - main
      - develop
      - staging
    paths:
      - 'app/**'
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy infrastructure?'
        required: false
        default: 'false'   

#permissions:
#  id-token: write
#  contents: read

jobs:
  build-push:
    uses: ./.github/workflows/build-push.yml
    with:
      env: ${{ inputs.env}}

  terraform:
    needs: build-push
    uses: ./.github/workflows/terraform.yml
    with:
      env: ${{ inputs.env }}
      config-path: 'terraform/${{ inputs.env }}.tfvars'

  
