name: Docker Build & Push to Artifact Registry

on:
  push:
    branches:
      - main
      - develop
      - staging

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.setenv.outputs.env }}
    steps:
      - id: setenv
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            echo "env=beta" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

  docker-build-push:
    needs: set-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/172250116490/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: ${{ vars.SA_NAME }}
          project_id: oceanic-muse-464012-k2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Set Image Name
        id: image
        run: |
          ENV="${{ needs.set-env.outputs.env }}"
          IMAGE_URI="europe-west1-docker.pkg.dev/oceanic-muse-464012-k2/${ENV}-repo/python-service-${ENV}:${ENV}-${GITHUB_SHA}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Docker Build
        run: |
          docker build -t $IMAGE_URI ./app

      - name: Docker Push
        run: |
          docker push $IMAGE_URI
