name: Destroy Terraform Resources

on:
  push:
    branches:
      - main
      - develop
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Authenticate to GCP via Workload Identity
              uses: google-github-actions/auth@v2
              with:
                workload_identity_provider: 'projects/172250116490/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
                service_account: ${{ vars.SA_NAME }}
                project_id: oceanic-muse-464012-k2

            - name: Terraform Destroy
              run: |
                terraform destroy -auto-approve \
                -var-file="${{ vars.env }}/${{ vars.env }}.tfvars"
              working-directory: terraform