name: Destroy Terraform Resources

on:
  push:
    branches:
      - main
      - develop
      - staging
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to destroy resources in'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Authenticate to GCP via Workload Identity
              uses: google-github-actions/auth@v2
              with:
                workload_identity_provider: 'projects/172250116490/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
                service_account: ${{ vars.SA_NAME }}
                project_id: oceanic-muse-464012-k2
            
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init -backend-config="${{ inputs.env }}/${{ inputs.env }}.backend.config"
              working-directory: terraform

            - name: Terraform Destroy
              run: |
                terraform destroy -auto-approve \
                -var-file="${{ inputs.env }}/${{ inputs.env }}.tfvars"
              working-directory: terraform